from src.pkg.rules.register_rules import rule_runner


def test_shared_rule_runner_includes_all_expected_syntax_rule_codes() -> None:
    codes = {rule.code for rule in rule_runner._rules}

    assert {
        "NO_BLOCKING_SEQUENTIAL",
        "NO_NONBLOCKING_COMBINATIONAL",
        "DEFAULT_CASE",
        "NO_CASEX_CASEZ",
        "NO_FULL_PARALLEL_CASE",
        "NO_MIXED_ASSIGNMENT_STYLE",
        "NO_INITIAL_BLOCK",
        "NO_FINAL_BLOCK",
        "NO_ALWAYS_FF",
        "NO_ALWAYS_LATCH",
        "NO_CASE_GENERATE",
        "NO_CASE_INSIDE",
        "NO_CHECKER_DECLARATION",
        "NO_CLOCKING_DECLARATION",
        "NO_DISABLE_STATEMENT",
        "NO_DO_WHILE_LOOP",
        "NO_EVENT_TRIGGER",
        "NO_FOR_LOOP",
        "NO_FOREACH_LOOP",
        "NO_GENERATE_FOR",
        "NO_IF_GENERATE",
        "NO_INTERFACE_DECLARATION",
        "NO_MODPORT_DECLARATION",
        "NO_PACKAGE_DECLARATION",
        "NO_PROGRAM_DECLARATION",
        "NO_TASK_DECLARATION",
        "NO_FORK_JOIN",
        "NO_FOREVER_LOOP",
        "NO_INSIDE_OPERATOR",
        "NO_REPEAT_LOOP",
        "NO_WAIT_STATEMENT",
        "NO_WHILE_LOOP",
        "NO_PRIORITY_IF",
        "NO_UNIQUE0_CASE",
        "NO_UNIQUE_IF",
        "NO_UNIQUE_PRIORITY_CASE",
        "NO_LATCH_IN_ALWAYS_COMB",
        "NO_DEFPARAM",
        "NO_FORCE_RELEASE",
        "NO_ASSIGN_DEASSIGN",
        "NO_WAND_WOR",
        "NO_TRIREG",
        "NO_SUPPLY0_SUPPLY1",
        "NO_TRAN_RTRAN",
        "NO_TRANIF_RTRANIF",
        "NO_SPECIFY_BLOCK",
        "NO_PRIMITIVE_DECLARATION",
        "NO_GATE_PRIMITIVE",
        "NO_ALIAS_STATEMENT",
        "NO_BIND_DIRECTIVE",
        "NO_DELAY_CONTROL",
        "NO_IMMEDIATE_ASSERTION",
        "NO_CONCURRENT_ASSERTION",
        "NO_DISPLAY_SYSTEM_TASK",
        "NO_SIMULATION_CONTROL_TASK",
    }.issubset(codes)
