"""Maps each tests/data/ fixture to the test files that reference it.

Fixtures are reused across many test files (some by a dozen or more), so a
change to one fixture can silently affect tests far from wherever the change
was made. This module is the generator behind docs/FIXTURE_USAGE.md -- see
tests/meta/test_fixture_usage_doc.py for how the checked-in doc is kept in sync.
"""

from __future__ import annotations

import re
from pathlib import Path

SUPPORT_DIR = Path(__file__).parent
TESTS_DIR = SUPPORT_DIR.parent
DATA_DIR = TESTS_DIR / "data"
REPO_ROOT = TESTS_DIR.parent

# This module's own docstring/comments name fixtures as examples; excluding it
# (and the generator's test) avoids counting those mentions as real usage.
_EXCLUDED_FILES = {SUPPORT_DIR / "fixture_usage.py"}


def _reference_pattern(fixture_name: str) -> re.Pattern[str]:
    # A fixture name can be a substring of an unrelated longer filename (e.g.
    # "a.sv" inside "data.sv"); require the match not be glued to a preceding
    # or following filename character so only whole-filename references count.
    return re.compile(rf"(?<![\w.]){re.escape(fixture_name)}(?!\w)")


def collect_fixture_usage() -> dict[str, list[str]]:
    """Return {fixture_filename: sorted repo-relative test file paths that reference it}."""
    import os

    fixture_names = sorted(p.name for p in DATA_DIR.iterdir() if p.is_file())
    test_files: list[Path] = []
    for root, dirs, files in os.walk(TESTS_DIR):
        dirs[:] = [d for d in dirs if not d.startswith((".", "_")) and d != "data"]
        for f in files:
            if f.endswith(".py"):
                p = Path(root) / f
                if p not in _EXCLUDED_FILES:
                    test_files.append(p)
    test_files.sort()

    file_contents = {}
    for p in test_files:
        text = p.read_text(encoding="utf-8", errors="ignore")
        if ".v" in text or ".sv" in text:
            file_contents[p] = text

    patterns = {name: _reference_pattern(name) for name in fixture_names}
    usage: dict[str, list[str]] = {}
    for name in fixture_names:
        pattern = patterns[name]
        referencing = [
            path.relative_to(REPO_ROOT).as_posix()
            for path, text in file_contents.items()
            if name in text and pattern.search(text)
        ]
        usage[name] = sorted(referencing)
    return usage


def render_fixture_usage_doc(usage: dict[str, list[str]]) -> str:
    lines = [
        "# Fixture Usage",
        "",
        "Generated by `tests/support/fixture_usage.py`; kept in sync by "
        "`tests/meta/test_fixture_usage_doc.py`. Regenerate after adding, removing, or "
        "renaming a reference to a `tests/data/` fixture:",
        "",
        "```",
        "UPDATE_EXPECTED=1 pytest tests/meta/test_fixture_usage_doc.py",
        "```",
        "",
        "A fixture referenced from several test files is exercised by all of them at "
        "once: a change to its RTL should be checked against every row it appears in, "
        "and an unintended parse or semantic change there can surface as unrelated-looking "
        "failures across files. See `tests/test_fixture_validity.py` for the parser-error "
        "check that fixtures must also pass regardless of how many tests reference them.",
        "",
        "This is a textual scan for literal filename references, so it misses tests that "
        "discover fixtures dynamically instead of naming them. Known gaps not reflected "
        "below: `tests/test_fixture_validity.py` parses every file in `tests/data/` "
        "regardless of name, and `tests/test_run_lint.py`'s "
        "`test_collect_paths_deduplicates_overlapping_inputs` / "
        "`test_run_does_not_duplicate_diagnostics_for_overlapping_inputs` pass the whole "
        "`tests/data` directory to the linter, exercising every fixture in it.",
        "",
    ]

    unused = sorted(name for name, files in usage.items() if not files)
    if unused:
        lines.append(
            f"## Unreferenced fixtures ({len(unused)})"
        )
        lines.append("")
        lines.append(
            "Not read by any test file. Confirm before deleting -- a fixture can still be "
            "referenced indirectly (for example, listed by name in documentation) without "
            "appearing here."
        )
        lines.append("")
        for name in unused:
            lines.append(f"- `tests/data/{name}`")
        lines.append("")

    lines.append("## All fixtures")
    lines.append("")
    lines.append("| Fixture | Used by | Referencing tests |")
    lines.append("|---|---|---|")
    for name in sorted(usage):
        files = usage[name]
        referencing = "-" if not files else "<br>".join(f"`{f}`" for f in files)
        lines.append(f"| `tests/data/{name}` | {len(files)} | {referencing} |")
    lines.append("")

    return "\n".join(lines)


__all__ = ["collect_fixture_usage", "render_fixture_usage_doc"]
