# src/pkg/handlers/register_handlers.py

from ..walk.dispatch import dispatch

from .default_handler import DefaultHandler

from .token_handler import TokenHandler
from .syntax_node_handler import SyntaxNodeHandler
from .module_declaration_handler import ModuleDeclarationHandler
from .function_declaration_handler import FunctionDeclarationHandler
from .package_import_handler import PackageImportHandler
from .primitive_declaration_handler import PrimitiveDeclarationHandler

# blocks
from .clocking_declaration_handler import ClockingDeclarationHandler
from .procedural_block_handler import ProceduralBlockHandler
from .case_statement_handler import CaseStatementHandler
from .case_generate_handler import CaseGenerateHandler
from .for_loop_statement_handler import ForLoopStatementHandler
from .type_and_generate_scope_handler import StructUnionTypeHandler, LoopGenerateHandler
from .typedef_declaration_handler import TypedefDeclarationHandler

#  variables
from .signal_event_expression_handler import SignalEventExpressionHandler
from .declarator_handler import DeclaratorHandler
from .identifier_name_handler import IdentifierNameHandler

# instantiation
from .hierarchy_instantiation_handler import HierarchyInstantiationHandler
